import { Injectable } from '@angular/core';
import { Foods } from 'src/app/shared/models/food';
import { Tag } from 'src/app/shared/models/Tag';
@Injectable({
  providedIn: 'root'
})
export class FoodService {

  constructor() { }

  getAllByTag(tag:string):Foods[]{
    if(tag == 'All'){
      return this.getAll();
    }
    else
      return this.getAll().filter(food=> food.tags?.includes(tag));
    
  }

  getAllTags():Tag[]{
    return[
      {name:"All", count: 40},
      {name: "STARTER", count:10},
      {name:"MOMOS", count: 6},
      {name: "SOUP", count:6},
      {name:"RICE & NOODLES", count:8},
      // {name: "THH SPECIAL", count:5},
      {name: "SPECIAL DRINKS", count:5},
      // {name: "HOT DRINKS", count:7}
    ]
  }

  getAll():Foods[]{
    return[
      {
        id:1,
        name: 'French Fries',
        price: 50,
        cookTime: '5-10',
        favorite: false,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/french-fries.jpg',
        tags:['STARTER']
      },
      {
        id:2,
        name: 'Chicken Chili',
        price: 110,
        cookTime: '5-10',
        favorite: true,
        veg:false,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/chilli-chicken.jpg',
        tags:['STARTER']
      },
      {
        id:3,
        name: 'Steamed Momo',
        price: 50,
        cookTime: '5-10',
        favorite: true,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/steam-momos.png',
        tags:['MOMOS']
      },
      {
        id:4,
        name: 'Steamed Momo',
        price: 60,
        cookTime: '5-10',
        favorite: true,
        veg:false,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/steam-momos.png',
        tags:['MOMOS']
      },
      {
        id:5,
        name: 'Chili Momo',
        price: 70,
        cookTime: '5-10',
        favorite: true,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/chilli momo.jpg',
        tags:['MOMOS']
      },
      {
        id:6,
        name: 'Chili Momo',
        price: 80,
        cookTime: '5-10',
        favorite: true,
        veg:false,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/chilli momo.jpg',
        tags:['MOMOS']
      },
      {
        id:7,
        name: 'Schezwan Momo',
        price: 75,
        cookTime: '5-10',
        favorite: false,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/schezwan-momos.webp',
        tags:['MOMOS']
      },
      {
        id:8,
        name: 'Schezwan Momo ',
        price: 85,
        cookTime: '5-10',
        favorite: false,
        veg:false,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/schezwan-momos.webp',
        tags:['MOMOS']
      },
      {
        id:9,
        name: 'Jhol Momo',
        price: 70,
        cookTime: '5-10',
        favorite: false,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/jhol momo.jpg',
        tags:['MOMOS']
      },
      {
        id:10,
        name: 'Jhol Momo',
        price: 80,
        cookTime: '5-10',
        favorite: false,
        veg:false,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/jhol momo.jpg',
        tags:['MOMOS']
      },
      {
        id:11,
        name: 'Tornado Potato',
        price: 30,
        cookTime: '5-10',
        favorite: false,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/tornado-potato.jpg',
        tags:['STARTER']
      },
      {
        id:12,
        name: 'Drums of Heaven',
        price: 130,
        cookTime: '5-10',
        favorite: false,
        veg:false,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/drums-of-heaven.jpg',
        tags:['STARTER']
      },
      {
        id:13,
        name: 'Crispy Chicken',
        price: 120,
        cookTime: '5-10',
        favorite: false,
        veg:false,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/crispy-chicken.webp',
        tags:['STARTER']
      },
      {
        id:14,
        name: 'Crispy Chili Corn',
        price: 80,
        cookTime: '5-10',
        favorite: false,
        veg:false,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/crispy-corn.jpg',
        tags:['STARTER']
      },
      {
        id:15,
        name: 'Spring Roll',
        price: 60,
        cookTime: '5-10',
        favorite: false,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/Spring-Roll-Recipe.jpg',
        tags:['STARTER']
      },
      {
        id:16,
        name: 'Spring Roll',
        price: 70,
        cookTime: '5-10',
        favorite: false,
        veg:false,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/Spring-Roll-Recipe.jpg',
        tags:['STARTER']
      },
      {
        id:17,
        name: 'Crispy Veg',
        price: 80,
        cookTime: '5-10',
        favorite: false,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/crispy-veg.jpg',
        tags:['STARTER']
      },
      {
        id:18,
        name: 'Thread Chicken',
        price: 120,
        cookTime: '5-10',
        favorite: false,
        veg:false,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/thread-chicken.jpg',
        tags:['STARTER']
      },
      {
        id:19,
        name: 'Chicken Lolipop',
        price: 120,
        cookTime: '5-10',
        favorite: true,
        veg:false,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/chicken-lollipop.jpg',
        tags:['STARTER']
      },
      {
        id:20,
        name: 'Chinese Bhel',
        price: 40,
        cookTime: '5-10',
        favorite: false,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/cb.webp',
        tags:['STARTER']
      },
      {
        id:21,
        name: 'Chinese Bhel',
        price: 50,
        cookTime: '5-10',
        favorite: false,
        veg:false,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/cb.webp',
        tags:['STARTER']
      },
      {
        id:22,
        name: 'Manchurian',
        price: 70,
        cookTime: '5-10',
        favorite: false,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/manchurian.jpg',
        tags:['STARTER']
      },
      {
        id:23,
        name: 'Manchurian',
        price: 110,
        cookTime: '5-10',
        favorite: false,
        veg:false,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/chicken-manchurian.jpg',
        tags:['STARTER']
      },
      {
        id:24,
        name: 'Manchow soup',
        price: 40,
        cookTime: '5-10',
        favorite: false,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/veg-manchow-soup.jpg',
        tags:['SOUP']
      },
      {
        id:25,
        name: 'Manchow Soup',
        price: 50,
        cookTime: '5-10',
        favorite: false,
        veg:false,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/veg-manchow-soup.jpg',
        tags:['SOUP']
      },
      {
        id:26,
        name: 'Sweet Corn Soup',
        price: 40,
        cookTime: '5-10',
        favorite: false,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/sweet corn soup.webp',
        tags:['SOUP']
      },
      {
        id:27,
        name: 'Sweet Corn Soup',
        price: 50,
        cookTime: '5-10',
        favorite: false,
        veg:false,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/sweet corn soup.webp',
        tags:['SOUP']
      },
      {
        id:29,
        name: 'Hot And Sour',
        price: 40,
        cookTime: '5-10',
        favorite: false,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/chinese-hot-and-sour-soup-sq.jpg',
        tags:['SOUP']
      },
      {
        id:30,
        name: 'Hot And Sour',
        price: 50,
        cookTime: '5-10',
        favorite: false,
        veg:false,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/chinese-hot-and-sour-soup-sq.jpg',
        tags:['SOUP']
      },
      {
        id:31,
        name: 'Noodle Soup',
        price: 40,
        cookTime: '5-10',
        favorite: false,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/Quick-Easy-Chinese-Noodle-Soup1200.jpg',
        tags:['SOUP']
      },
      {
        id:32,
        name: 'Noodle Soup',
        price: 50,
        cookTime: '5-10',
        favorite: false,
        veg:false,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/Quick-Easy-Chinese-Noodle-Soup1200.jpg',
        tags:['SOUP']
      },
      {
        id:33,
        name: 'Clear Soup',
        price: 30,
        cookTime: '5-10',
        favorite: false,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/clear soup.webp',
        tags:['SOUP']
      },
      {
        id:34,
        name: 'Clear Soup',
        price: 40,
        cookTime: '5-10',
        favorite: false,
        veg:false,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/clear soup.webp',
        tags:['SOUP']
      },
      {
        id:35,
        name: 'Lemonade',
        price: 30,
        cookTime: '5-10',
        favorite: false,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/lemonade.jpg',
        tags:['SPECIAL DRINKS']
      },
      {
        id:36,
        name: 'Lemon Mint',
        price: 40,
        cookTime: '5-10',
        favorite: false,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/Mint-Lemonade.jpg',
        tags:['SPECIAL DRINKS']
      },
      {
        id:37,
        name: 'Lemon Ice Tea',
        price: 30,
        cookTime: '5-10',
        favorite: false,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/lemon-Iced-Tea.jpg',
        tags:['SPECIAL DRINKS']
      },
      {
        id:38,
        name: 'Virgin Mojito',
        price: 50,
        cookTime: '5-10',
        favorite: false,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/Mojito.jpg',
        tags:['SPECIAL DRINKS']
      },
      {
        id:39,
        name: 'Banana Shake',
        price: 70,
        cookTime: '5-10',
        favorite: false,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/banana-smoothie.jpg',
        tags:['SPECIAL DRINKS']
      },
      {
        id:40,
        name: 'Chocolate Shake',
        price: 70,
        cookTime: '5-10',
        favorite: false,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/Ichocolate-shake.jpg',
        tags:['SPECIAL DRINKS']
      },
      {
        id:41,
        name: 'Cold Coffee With Ice-Cream',
        price: 80,
        cookTime: '5-10',
        favorite: true,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/Cold-Coffee.jpg',
        tags:['SPECIAL DRINKS']
      },
      {
        id:42,
        name: 'Fried Ice-cream',
        price: 80,
        cookTime: '5-10',
        favorite: false,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/fried-ice-cream-3.jpg',
        tags:['DESERTS']
      },
      {
        id:43,
        name: 'Crispy Honey Noodles',
        price: 80,
        cookTime: '5-10',
        favorite: false,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/Honey-Noodles-1-3.jpg',
        tags:['DESERTS']
      },
      {
        id:44,
        name: 'Fried Banana Ice-Cream',
        price: 80,
        cookTime: '5-10',
        favorite: false,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/fried-bananas-with-ice-cream.jpg',
        tags:['DESERTS']
      },
      {
        id:45,
        name: 'Ice-cream',
        price: 50,
        cookTime: '5-10',
        favorite: false,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/icecream.jpg',
        tags:['DESERTS']
      },
      {
        id:46,
        name: 'Fried Rice',
        price: 60,
        cookTime: '5-10',
        favorite: false,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/fried rice.webp',
        tags:['RICE & NOODLES']
      },
      {
        id:47,
        name: 'Fried Rice',
        price: 70,
        cookTime: '5-10',
        favorite: false,
        veg:false,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/fried rice.webp',
        tags:['RICE & NOODLES']
      },
      {
        id:48,
        name: 'Schezwan Fried Rice',
        price: 70,
        cookTime: '5-10',
        favorite: true,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/Schezwan-Fried-Rice-1-3.jpg',
        tags:['RICE & NOODLES']
      },
      {
        id:49,
        name: 'Schezwan Fried Rice',
        price: 80,
        cookTime: '5-10',
        favorite: true,
        veg:false,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/Schezwan-Fried-Rice-1-3.jpg',
        tags:['RICE & NOODLES']
      },
      {
        id:50,
        name: 'Shanghai Rice',
        price: 70,
        cookTime: '5-10',
        favorite: false,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/shanghai rice.jpg',
        tags:['RICE & NOODLES']
      },
      {
        id:51,
        name: 'Shanghai Rice',
        price: 80,
        cookTime: '5-10',
        favorite: false,
        veg:false,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/shanghai rice.jpg',
        tags:['RICE & NOODLES']
      },
      {
        id:52,
        name: 'Singapore Rice',
        price: 60,
        cookTime: '5-10',
        favorite: false,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/singapore-fried-rice.jpg',
        tags:['RICE & NOODLES']
      },
      {
        id:53,
        name: 'Singapore Rice',
        price: 70,
        cookTime: '5-10',
        favorite: false,
        veg:false,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/singapore-fried-rice.jpg',
        tags:['RICE & NOODLES']
      },
      {
        id:54,
        name: 'Hakka Noodles',
        price: 70,
        cookTime: '5-10',
        favorite: true,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/Chicken-Hakka-Noodles-Recipe.jpg',
        tags:['RICE & NOODLES']
      },
      {
        id:55,
        name: 'Hakka Noodles',
        price: 80,
        cookTime: '5-10',
        favorite: true,
        veg:false,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/Chicken-Hakka-Noodles-Recipe.jpg',
        tags:['RICE & NOODLES']
      },
      {
        id:56,
        name: 'Schezwan Noodles',
        price: 70,
        cookTime: '5-10',
        favorite: true,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/Schezwan-Noodles.webp',
        tags:['RICE & NOODLES']
      },
      {
        id:57,
        name: 'Schezwan Noodles',
        price: 80,
        cookTime: '5-10',
        favorite: true,
        veg:false,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/Schezwan-Noodles.webp',
        tags:['RICE & NOODLES']
      },
      {
        id:58,
        name: 'Combo Meal',
        price: 145,
        cookTime: '5-10',
        favorite: false,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/',
        tags:['THH SPECIAL']
      },
      {
        id:59,
        name: 'Combo Meal',
        price: 165,
        cookTime: '5-10',
        favorite: false,
        veg:false,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/',
        tags:['THH SPECIAL']
      },
      {
        id:60,
        name: 'Triple Schezwan',
        price: 165,
        cookTime: '5-10',
        favorite: false,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/',
        tags:['THH SPECIAL']
      },
      {
        id:61,
        name: 'Chicken Lung Fung Soup',
        price: 60,
        cookTime: '5-10',
        favorite: false,
        veg:false,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/',
        tags:['THH SPECIAL']
      },
      {
        id:62,
        name: 'Chicken Hot Corn Soup',
        price: 60,
        cookTime: '5-10',
        favorite: false,
        veg:false,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/',
        tags:['THH SPECIAL']
      },
      {
        id:63,
        name: 'Thukpa',
        price: 70,
        cookTime: '5-10',
        favorite: false,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/',
        tags:['THH SPECIAL']
      },
      {
        id:64,
        name: 'Thukpa',
        price: 80,
        cookTime: '5-10',
        favorite: false,
        veg:false,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/',
        tags:['THH SPECIAL']
      },
      {
        id:65,
        name: 'Black Tea',
        price: 10,
        cookTime: '5-10',
        favorite: false,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/.webp',
        tags:['HOT DRINKS']
      },
      {
        id:66,
        name: 'Milk Tea',
        price: 20,
        cookTime: '5-10',
        favorite: false,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/.webp',
        tags:['HOT DRINKS']
      },
      {
        id:67,
        name: 'Black Coffee',
        price: 20,
        cookTime: '5-10',
        favorite: false,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/.webp',
        tags:['HOT DRINKS']
      },
      {
        id:68,
        name: 'Milk Coffee',
        price: 30,
        cookTime: '5-10',
        favorite: false,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/.webp',
        tags:['HOT DRINKS']
      },
      {
        id:69,
        name: 'Lemon Tea',
        price: 25,
        cookTime: '5-10',
        favorite: false,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/.webp',
        tags:['HOT DRINKS']
      },
      {
        id:70,
        name: 'Masala Tea',
        price: 25,
        cookTime: '5-10',
        favorite: false,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/.webp',
        tags:['HOT DRINKS']
      },
      {
        id:71,
        name: 'Ginger Tea',
        price: 25,
        cookTime: '5-10',
        favorite: false,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/.webp',
        tags:['HOT DRINKS']
      },
      {
        id:72,
        name: 'Hot Chocolate',
        price: 50,
        cookTime: '5-10',
        favorite: false,
        veg:true,
        origins: ['italy'],
        star:['1','1','1','1','1'],
        imageUrl:'/assets/.webp',
        tags:['HOT DRINKS']
      }
      
    ];
  }
}
